const assert=require('node:assert/strict');
const a=require('../public/asset-understanding.js');
const item={id:'fixture',kind:'video',file:{name:'coast.mp4'},metadata:{width:3840,height:2160,duration:28,fps:60,hasAudio:true,capturedAt:'2025:07:19 10:00:00'},result:{analysis:{assetUnderstanding:{summary:'Coastal cliffs above breaking waves',subjects:['Cliffs','Ocean'],scene:['Coast','Outdoors'],actions:['Breaking waves'],location:{country:'USA',city:'Big Sur'},capture:{cameraMode:'drone',shotSize:'extreme_wide',cameraMotion:'push'},editing:{shotRole:'establishing',importance:.9,recommendedUse:'chapter_open',suggestedDuration:{min:3,max:5}},quality:{overall:.9,sharpness:92,stability:0,issues:[]},audio:{hasSpeech:false,hasUsefulAmbientSound:true,ambientTypes:['Waves'],audioQuality:.85}},subtitleCues:[{start:0,end:2,text:'The ocean is incredible'}]}}};
const asset=a.normalize(item),card=a.buildAssetCard(asset);
assert.equal(card.title,'coast');assert.equal(card.summary,'Coastal cliffs above breaking waves');
assert.equal(a.buildAssetCard(a.normalize({...item,title:'Pacific coast trip'})).title,'Pacific coast trip');
assert.equal(a.buildAssetCard(a.normalize({...item,metadata:{title:'Weekend in Big Sur'}})).title,'Weekend in Big Sur');
assert.equal(card.captureLabel,'Drone');assert.equal(card.primaryRole,'Establishing');
assert.deepEqual(card.tags,['Extreme wide','Push in','Highlight']);
assert.deepEqual(card.discoveryTags,['Big Sur','2025-07-19']);
for(const tag of card.discoveryTags)assert.ok(a.matches(asset,{},tag),'Every discovery tag is searchable');
const photo=a.normalize({kind:'image',file:{name:'luxury.jpg'},metadata:{width:1280,height:720}});
assert.deepEqual(a.buildAssetCard(photo).discoveryTags,[],'Do not pad missing context with orientation or extension');
for(const tag of a.buildAssetCard(photo).discoveryTags)assert.ok(a.matches(photo,{},tag));
const sceneOnly=a.normalize({kind:'video',file:{name:'clip.mp4'},assetUnderstanding:{scene:['City walk'],subjects:['Street']}});
assert.deepEqual(a.buildAssetCard(sceneOnly).discoveryTags,['City walk','Street']);
assert.deepEqual(a.buildAssetCard(a.normalize({kind:'video',file:{name:'unknown'}})).discoveryTags,[],'Do not invent context');
assert.deepEqual(card.status,['4K','60 fps','Useful ambience']);
assert.equal(asset.quality.stability,0,'Zero is a real score');
assert.equal(asset.quality.overall,90);assert.equal(asset.audio.audioQuality,85);
assert.ok(a.matches(asset,{content:'Ocean',editing:'Chapter opening'},'big sur ocean'));
assert.ok(a.matches(asset,{dateFrom:'2025-07-19',dateTo:'2025-07-19'},'2025-07-19'));
assert.ok(!a.matches(asset,{quality:'Dialogue'}));
assert.ok(a.searchText(asset).includes('the ocean is incredible'),'ASR/subtitle text is searchable');
const raw={id:'empty',kind:'video',file:{name:'drone_beach_highlight.mp4',lastModified:Date.now()},metadata:{width:1280,height:720,fps:120,hasAudio:true},result:{analysis:{hookScore:95,formatGuess:'Talking head',segments:[{role:'Hook'}],subtitleCues:[{start:0,end:2,text:'This could be a title card'}]}}};
const unknown=a.normalize(raw),fallback=a.buildAssetCard(unknown);
assert.equal(fallback.title,'drone_beach_highlight');assert.equal(fallback.captureKey,null,'High fps is not proof of slow motion');
assert.equal(fallback.primaryRole,'');assert.equal(fallback.highlight,false,'Never use legacy heuristic hook scores');
assert.equal(unknown.audio.hasSpeech,null,'Embedded captions do not prove dialogue');assert.equal(unknown.quality.overall,null);
assert.ok(!a.matches(unknown,{dateFrom:'2020-01-01'}),'Unknown shooting date cannot pass a date filter');
assert.ok(!a.matches(a.normalize({...raw,metadata:{capturedAt:'not-a-date'}}),{dateFrom:'2020-01-01'}));
assert.deepEqual(a.normalize(item,{start:3,end:8}).subjects,[],'Whole-video semantics must not leak to individual shots');
const bad=a.normalize({...raw,assetUnderstanding:{},result:{analysis:{assetUnderstanding:{summary:34,subjects:'people',capture:{cameraMode:'constructor'},editing:{importance:12,suggestedDuration:{min:8,max:2}},quality:{overall:-1},audio:{hasSpeech:'true'}}}}});
assert.equal(bad.capture.cameraMode,null);assert.equal(bad.editing.importance,null);assert.equal(bad.editing.suggestedDuration,null);assert.equal(bad.audio.hasSpeech,null);
for(const key of Object.keys(a.labels.cameraMode))assert.ok(a.capturePaths[key]);
const fs=require('node:fs'),path=require('node:path'),html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8'),js=fs.readFileSync(path.join(__dirname,'../public/library.js'),'utf8');
assert.doesNotMatch(html,/data-asset-filter=/,'Understanding remains searchable without advanced filter controls');
assert.match(js,/item\.favorite=!item\.favorite;await save\(item\)/);
assert.doesNotMatch(js,/asset-detail-tabs|role','tablist|panels\.transcript/,'Details use continuous sections, not tabs');
assert.match(js,/byId\('mediaDetailTitle'\)\.textContent=asset\.title/);
assert.doesNotMatch(js,/Scene analysis unavailable|Scene analysis is not available|shot-filename/,'No placeholder or duplicate filename text on cards');
assert.match(html,/class="media-detail-close"[^>]*aria-label="Close media details"[^>]*><svg/);
assert.doesNotMatch(js,/innerHTML/);
console.log('PASS: Semantic cards, truthful fallbacks, icon vocabulary, searchable metadata, transcript search, favorite persistence and full detail mapping.');
