const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {kindOf,duration,size}=require('../public/library.js');
for(const name of ['trip.mp4','trip.MOV','trip.mkv'])assert.equal(kindOf({name,type:''}),'video');
for(const name of ['photo.jpg','photo.HEIC','photo.avif'])assert.equal(kindOf({name,type:''}),'image');
assert.equal(kindOf({name:'notes.txt',type:'text/plain'}),null);
assert.equal(kindOf({name:'footage',type:'video/mp4'}),'video');
assert.equal(duration(125.9),'2:05');assert.equal(duration(0),'0:00');assert.equal(size(1048576),'1.0 MB');
const root=path.join(__dirname,'../public');const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'library.js'),'utf8');const css=fs.readFileSync(path.join(root,'library.css'),'utf8');
assert.match(html,/id="fileInput"[^>]*accept="video\/\*,image\/\*/);
assert.doesNotMatch(html.match(/<input id="fileInput"[^>]*>/)[0],/multiple/,'Web picker selects one file');
assert.match(js,/if\(!desktop\)return/,'Native library is not initialized on web');
assert.match(js,/byId\('fileInput'\)\.multiple=true/,'Mac retains multiple-file importing');
assert.match(html,/id="folderInput"[^>]*webkitdirectory[^>]*multiple/);
for(const page of ['home','media','skills'])assert.match(html,new RegExp('data-workspace-page="'+page+'"'));
assert.match(html,/id="workspaceHome"/);assert.match(html,/id="workspaceSkills"/);
assert.match(js,/byId\('libraryTitle'\)\.textContent=page==='home'\?'Home':page==='history'\?'Project':page==='skills'\?'Skills':'Media';/,'Category tabs must not change the Media heading');
assert.match(js,/const total=items\.filter\(i=>i.kind==='video'\)\.reduce/,'Header video duration always describes the entire library, not the current category');
assert.deepEqual([...html.matchAll(/data-library-view="([^"]+)"/g)].map(match=>match[1]),['all','video','image','favorites'],'Favorites is a peer category');
assert.doesNotMatch(html+js,/assetFiltersToggle|assetFilterPanel|facetFilters|favoritesOnly|relatedTagFilters|favoriteFilter/,'No stacked filter state or controls');
assert.match(js,/el\('h3','Transcript'\)/,'Transcript stays available in media details');
const home=html.split('<div id="workspaceHome" hidden>')[1].split('<section id="workspaceSkills"')[0];
assert.doesNotMatch(html,/class="library-topbar"/,'Workspace has no redundant top navigation');
assert.doesNotMatch(home,/Watch sample|YOUR FIRST FEW MINUTES|A LITTLE INSPIRATION|home-stats|home-actions/,'Home avoids repeated marketing descriptions');
for(const id of ['homeMediaGrid','homeMediaTitle','showcaseTitle','homeSkillsTitle','tutorialTitle'])assert.ok(home.includes(`id="${id}"`));
for(const id of ['homeMediaTitle','showcaseTitle','homeSkillsTitle','tutorialTitle'])assert.match(home,new RegExp(`<h2 id="${id}">[^<]+</h2><p>[^<]+</p>`),'Home section headings have a concise description');
assert.equal((home.match(/class="home-action-card/g)||[]).length,2,'Keep two full-width feature entry cards');
assert.match(home,/In development/,'Web Mac entry clearly states development status');
assert.match(js,/for\(const item of homeGrid\?items\.slice\(-4\):\[\]\)/,'Legacy home rendering must tolerate the native composer replacing it');
assert.equal((html.match(/data-showcase="/g)||[]).length,3);
assert.equal((html.match(/data-skill="/g)||[]).length,4);
const skills=html.split('<section id="workspaceSkills"')[1].split('</section>')[0];
assert.doesNotMatch(skills,/<small>|<em>|skills-intro|class="library-scope"|aria-pressed="true"/,'Skills starts without selection or redundant copy');
assert.match(skills,/id="skillStatus" class="sr-only" role="status"/,'Selection announcements stay accessible without visible small print');
assert.doesNotMatch(js,/localStorage\.getItem\('pixfun-creative-skill'\)|target\?\.focus\(/,'Do not restore default card highlighting or auto-focus a skill');
assert.match(js,/xhr\.upload\.onprogress/);assert.match(js,/xhr\.ontimeout/);assert.match(js,/xhr\.onabort/);
assert.doesNotMatch(html+js+css,/libraryProgress|library-progress/,'Import progress must live in media tiles, not a separate panel');
assert.match(js,/preview\.append\(overlay\)/);assert.match(js,/updateTileProgress\(item\)/);
assert.match(js,/aria-valuenow/);assert.match(css,/prefers-reduced-motion:reduce/);
assert.match(html,/id="libraryImportStatus"[^>]*role="status"/);
assert.match(js,/500\*1024\*1024/);assert.match(js,/chosen\.slice\(0,100\)/);
assert.match(js,/indexedDB\.open/);assert.match(js,/status='cancelled'/);
assert.doesNotMatch(js,/innerHTML/,'User filenames and subtitles must be escaped through textContent');
assert.match(js,/preview\.currentTime=start/);assert.match(js,/preview\.currentTime=cue\.start/);assert.match(js,/\.showModal\(\)/);
assert.match(css,/@media\(max-width:820px\)/);assert.match(css,/focus-visible/);
const library=html.split('<section id="mediaLibrary"')[1].split('<dialog id="showcaseDialog"')[0];
assert.doesNotMatch(library,/class="timeline/,'No editing timeline during ingestion');
assert.match(html,/<dialog id="mediaDetailDialog" aria-labelledby="mediaDetailTitle"/);
assert.doesNotMatch(library,/<aside class="library-inspector"/,'Details no longer take a permanent grid column');
assert.match(js,/byId\('mediaDetailDialog'\)\.showModal\(\)/);
assert.match(js,/assets\.matches\(assets\.normalize\(item,segment\)/,'Search and filters use normalized understanding');
assert.match(js,/if\(!byId\('mediaDetailDialog'\)\.open\)return/,'Do not load hidden detail players');
assert.doesNotMatch(library,/Available now: file details/,'No redundant capability footer in Media');
assert.doesNotMatch(js,/library-content>\.library-scope/,'Do not reference the removed footer');
console.log('PASS: Media types, limits, multi-file/folder inputs, workspace routes, real analysis states, safe content, tutorials and showcase controls.');
