const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {travelScrollState,workflowPresentation} = require('../public/travel.js');
const root = path.resolve(__dirname,'../public');
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
const css = fs.readFileSync(path.join(root,'travel.css'),'utf8');
const script = fs.readFileSync(path.join(root,'travel.js'),'utf8');
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);
assert.equal(ids.length,new Set(ids).size,'No duplicate element IDs');
assert.equal((html.match(/class="brand-logo"/g)||[]).length,2,'Selected lockup in navigation and footer');
assert.equal((html.match(/alt="Pixfun"/g)||[]).length,4,'Capital P in navigation, footer, library and standalone analysis brand labels');
assert.match(html,/rel="icon"[^>]*pixfun-icon-v2\.png/,'Browser favicon uses the selected film-cut mark');
assert.match(html,/rel="apple-touch-icon"[^>]*pixfun-icon-v2\.png/);
assert.doesNotMatch(html,/brand-compass|travel-compass\.svg/,'No legacy compass remains in the displayed brand');
assert.doesNotMatch(html,/brand-wordmark">pixfun/,'No old lowercase lockup remains');
const brandCss = fs.readFileSync(path.join(root,'brand-voices.css'),'utf8');
assert.match(brandCss,/filter:url\('\/assets\/images\/logo-effects\.svg#clear-black'\)/,'Remove the logo matte on both header and footer');
assert.match(fs.readFileSync(path.join(root,'images/logo-effects.svg'),'utf8'),/id="clear-black"/,'Logo compositing filter exists');
for(const id of ['urlForm','urlInput','uploadBtn','fileInput','results','sourceVideo','timeline','subtitleLane','directionConversation','briefForm','textForm','renderForm','confirmConversation','heroFilm','demoImage','demoHeading','demoSceneInsights','demoFilmDirection','stylePicker']) assert.ok(ids.includes(id),id);
for(const match of html.matchAll(/(?:src|href)="(\/assets\/[^"?]+)(?:\?[^" ]*)?"/g)) assert.ok(fs.existsSync(path.join(root,match[1].replace('/assets/',''))),match[1]);
const heroNames = ['citywalk','food','outdoors','islands','alpine'];
for(const name of heroNames) {
  assert.ok(fs.statSync(path.join(root,'media/cases',name+'-preview.mp4')).size>10000);
  assert.ok(fs.statSync(path.join(root,'media/cases',name+'.jpg')).size>1000);
  assert.match(html,new RegExp('data-film="'+name+'"'));
}
assert.equal([...html.matchAll(/<button[^>]*data-stage="[0-5]"/g)].length,6);
for(const index of [0,1,2,3,4,5,2,0,3,0]) {
  const view=workflowPresentation(index);
  assert.equal(view.sources,index===0,'Import shows a many-clip library');
  assert.equal(view.viewer,index>0,'Preview is shared by understanding, style and editing');
  assert.equal(view.timeline,index>=3,'Timeline starts with arrangement, including reverse navigation');
  assert.equal(view.labels,index===1);
  assert.equal(view.styles,index===2);
}
assert.match(html, /id="demoTimeline"[^>]*hidden/,'No timeline flash before JavaScript initializes');
assert.match(html, /id="demoViewer"[^>]*hidden/);
assert.equal([...html.matchAll(/class="source-insight" hidden/g)].length,0,'Source cards are footage, not repeated analysis copy');
assert.match(script, /setStage\(0\);\s*manageVideo\(\)/,'Initialize presentation explicitly');
assert.equal((html.split('id="demoSources"')[1].split('id="demoViewer"')[0].match(/<figure>/g)||[]).length,12);
assert.doesNotMatch(html,/id="demo(?:StageLabel|Availability|ContextLabel|SourceNote|SourceTitle|ImageCaption|Time)"/,'No duplicate stage headers, media caption strip or source footer');
assert.match(html,/class="demo-summary"><h3 id="demoHeading"/,'One heading shared by the entire active stage');
assert.match(html,/id="demoImport"><h4>/,'Import has a concise project brief rather than an empty sidebar');
assert.doesNotMatch(html,/id="demoDirection"|class="workflow-note"/,'No redundant bottom commentary');
assert.doesNotMatch(html,/id="demoDevices"/,'Do not invent capture devices for stock footage');
for (const id of ['demoUnderstanding','demoArrange','demoRefine','demoFinish']) {
  assert.ok(ids.includes(id),'Distinct action view: '+id);
  assert.ok(script.includes("'"+id+"'"),'Phase-specific visibility: '+id);
}
assert.match(script,/poster\.src=mediaRoot\+shot\.image\+'\.jpg'/,'Static preview uses the selected story frame');
for(let i=0;i<6;i++) assert.equal(travelScrollState(-((i+.2)/6)*2400,3200,800).stage,i);
assert.deepEqual(travelScrollState(100,3200,800),{progress:0,stage:0,playhead:4});
assert.deepEqual(travelScrollState(-9999,3200,800),{progress:1,stage:5,playhead:95});
for(let i=0;i<=1000;i++) {const s=travelScrollState(-i*3,3800,800);assert.ok(s.stage>=0&&s.stage<=5);assert.ok(s.playhead>=4&&s.playhead<=95);}
assert.match(css,/prefers-reduced-motion/);
assert.match(script,/IntersectionObserver/);
assert.match(css,/\.travel-workflow\.is-scrollable \.workflow-sticky\{justify-content:flex-start\}/,'Pinned workflow heading must not move when the active step changes height');
const player = fs.readFileSync(path.join(root,'hero-player.js'),'utf8');
assert.match(player,/video\.pause\(\)/);
assert.match(html,/ROAD TRIPS &amp; OUTDOOR ESCAPES/);
assert.match(html,/CITY WALKS &amp; CITY BREAKS/);
assert.match(html,/FOOD &amp; CAFÉ DISCOVERIES/);
assert.match(html,/FLIGHTS &amp; SPECIAL STAYS/);
assert.match(html,/<title>Pixfun — AI Video Editing for Travel Creators<\/title>/);
const headline=html.split('<h1 id="heroTitle">')[1].split('</h1>')[0];
assert.equal((headline.match(/class="hero-title-line"/g)||[]).length,2,'Two explicit headline lines');
assert.match(headline,/Turn your travel footage into/);
assert.match(headline.replace(/<[^>]+>/g,''),/beautiful films, 10× faster\./,'Preserve the historical hero copy explicitly requested by the user');
assert.match(headline,/<span class="hero-multiplier">10<span class="hero-times">×<\/span><\/span>/,'Restore the original warm-gold multiplier treatment');
assert.doesNotMatch(html,/Powered by AI/,'Avoid a generic AI slogan in the headline');
assert.doesNotMatch(html,/class="hero-efficiency"/,'No separate small-print efficiency claim');
assert.doesNotMatch(html,/That’s our goal|Our goal:|first cut/i,'Position full creative editing rather than only quick first cuts');
assert.match(html,/Is Pixfun only for quick highlight reels/);
assert.match(html,/not a live video generator/,'Separate the demonstration from live editing');
assert.doesNotMatch(html,/<button[^>]*data-upload/,'The landing has no upload CTA');
assert.match(html,/<div hidden><button[^>]*id="uploadBtn"/,'Legacy upload binding is kept inside a permanently hidden container');
assert.match(html,/id="downloadMac"[^>]*>Apply for early access /);
assert.doesNotMatch(html,/id="headerApply"|application-cta/,'No top-right CTA or oversized hero application button');
assert.match(html,/<div class="home-header-actions" hidden>/,'Legacy header actions remain hidden');
assert.doesNotMatch(brandCss,/#downloadMac\{|#headerApply\{/,'Application uses shared button sizing');
for (const file of ['index.html', 'pixfun.js', 'app.js', 'travel.js', 'polish.js', 'hero-player.js']) {
  assert.doesNotMatch(fs.readFileSync(path.join(root, file), 'utf8'), /\p{Script=Han}/u, `${file} keeps built-in website copy in English`);
}
assert.match(html,/AI that understands your scenes, actions, and key moments\./);
assert.match(html,/Find the shots worth keeping\. Give every clip a place in your story\./);
const example = html.split('id="stories"')[1].split('<section class="travel-workflow"')[0];
assert.match(example,/Turn a trip’s worth of footage into one complete travel film\./);
for(const [id,copy] of Object.entries({workflowTitle:'See how your footage becomes a finished travel film.',creatorsTitle:'Create travel videos that match the way you explore.',voicesTitle:'Who is Pixfun for?',faqTitle:'A few things to know.',closingTitle:'Help shape Pixfun for Mac.'})) {
  assert.ok(html.includes(`<h2 id="${id}">${copy}</h2>`),`${id} uses the approved complete sentence without forced italic fragments`);
}
assert.match(example,/>INPUT</);
assert.match(example,/>OUTPUT</);
assert.equal((example.split('class="source-pile"')[1].split('</ul>')[0].match(/<li>/g)||[]).length,8,'Eight stacked sample thumbnails');
assert.match(example,/96 clips · 2 hr 18 min/);
assert.match(example,/\+88 more clips/);
assert.match(css,/\.source-pile img\{[^}]*height:auto;[^}]*aspect-ratio:16\/10/,'Responsive thumbnail height must override intrinsic HTML height');
assert.match(example,/<figure class="example-cover"/,'Output is a static cover, not a player');
assert.match(example,/>1080p · 16:9</,'Example output is labeled Full HD');
assert.doesNotMatch(html,/\b720p\b/i,'Do not display the old 720p label');
assert.match(example,/class="cover-travelers"/,'Travel cover pairs real travelers with scenery');
assert.match(example,/ONE WEEK<br><em>AWAY\.<\/em>/,'Cover has a short, legible video headline');
assert.ok([...css.matchAll(/--tilt:(-?\d+)deg/g)].every(match=>Math.abs(Number(match[1]))<=3),'Source pile keeps only a subtle tilt');
assert.match(example,/datetime="PT20M18S"/);
assert.doesNotMatch(example,/<video|exampleFilm|travel-edit-example\.mp4|example-cut-order/);
assert.match(example,/Clip counts, durations, and cover are examples/);
assert.match(example,/Illustrative, not generated live/,'Do not imply current automatic multi-clip rendering');
assert.doesNotMatch(example,/contact-sheet|sequence-cards|value-notes/,'Replace ambiguous image galleries and generic benefits');
assert.match(css,/\.edit-example\{grid-template-columns:minmax\(0,1fr\)/,'Stack input before output on mobile');
const platforms = example.split('class="share-destinations"')[1];
assert.ok(platforms,'Sharing destinations follow the edited output');
assert.match(platforms,/Export your video, then upload it wherever you share\./,'Describe manual sharing, not direct publishing');
assert.equal((platforms.match(/<li>/g)||[]).length,4);
for(const platform of ['youtube','tiktok','instagram','facebook']) assert.match(platforms,new RegExp('/assets/images/platforms/'+platform+'\\.svg'));
assert.doesNotMatch(platforms,/<button|<a\s|onclick=/,'Destination logos are informative, not fake integrations');
assert.doesNotMatch(html,/Beautifully edited\.|Start editing|Intelligent editing\. Real moments/,'Remove superseded legacy marketing copy');
assert.match(html,/Workflow preview|WORKFLOW PREVIEW/);
assert.doesNotMatch(html,/speaker-|case-ai-|AI VIDEO CREATION|viral video formats|generated_images/);
assert.equal([...html.matchAll(/data-film="/g)].length,5,'Exactly five independent cases');
const previewHashes = heroNames.map(name=>require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(root,'media/cases',name+'-preview.mp4'))).digest('hex'));
assert.equal(new Set(previewHashes).size,5,'Every case must be a different actual video file');
assert.equal((html.match(/<small>View breakdown<\/small>/g)||[]).length,5,'Five cases link to the full-video breakdown');
const imageNames = section => [...section.matchAll(/<img[^>]*src="([^"]+)"/g)].map(m=>m[1]).filter(s=>s.includes('/media/travel/'));
const sourceImages = imageNames(html.split('class="source-grid"')[1].split('</div></div>')[0]);
assert.equal(new Set(sourceImages).size,12,'Twelve source cards show twelve genuinely different images');
const mediaHash = source => require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(root,source.replace('/assets/','')))).digest('hex');
assert.equal(new Set(sourceImages.map(mediaHash)).size,12,'No duplicate images under new filenames');
const creatorImages = imageNames(html.split('class="creator-grid"')[1].split('</div></section>')[0]);
assert.equal(creatorImages.length,4);
const inputImages = imageNames(example);
const heroImages = heroNames.map(n=>'/assets/media/travel/hero-'+n+'.jpg');
for(const source of creatorImages) assert.ok(![...sourceImages,...inputImages,...heroImages].includes(source),'Creator imagery is separate from other sections');
for(const source of sourceImages) assert.ok(![...inputImages,...heroImages].includes(source),'Workflow imagery is separate from hero and input/output');
const trackImages = imageNames(html.split('class="demo-track"')[1].split('</div></div>')[0]);
assert.ok(trackImages.every(source=>sourceImages.includes(source)),'Arrangement uses only clips introduced in the source library');
assert.doesNotMatch(html,/highlights\.mp4|watchHighlights/,'No cross-case highlight reel');
assert.match(player,/addEventListener\('ended'/,'Finished cases advance naturally');
assert.doesNotMatch(html.match(/<video id="heroFilm"[^>]*>/)[0],/\bloop\b/,'Native loop must not swallow ended');
console.log('PASS: Travel positioning, five independent real video cases, six bounded scroll stages, responsive motion fallback, preserved workspace DOM, and asset integrity.');
