const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {validate,kindOf,pending,time,repetitive,visualDescription,editingSummary}=require('../public/web-analysis.js');
const video={name:'Travel.mp4',type:'video/mp4',size:100},photo={name:'Coast.JPG',type:'',size:100};
assert.equal(validate([video]),'');assert.equal(validate([photo]),'');
assert.match(validate([video,photo]),/one/);assert.match(validate([]),/one/);
assert.match(validate([{...video,size:0}]),/500 MB/);
assert.match(validate([{...video,size:500*1024*1024+1}]),/500 MB/);
assert.equal(validate([{...video,size:500*1024*1024}]),'');
assert.match(validate([{name:'readme.txt',type:'text/plain',size:100}]),/video or photo/);
assert.equal(kindOf(photo),'image');assert.equal(kindOf(video),'video');
for(const status of ['reading','uploading','analyzing','understanding'])assert.ok(pending({status}));
assert.ok(repetitive('surprise '.repeat(100)));
assert.ok(!repetitive('Surprise! We arrived in the village just before sunset.'));
assert.equal(visualDescription({metadata:{duration:30,width:1080,height:1920}}),'','Metadata must not stand in for visual content');
const full='The foreground contains a sandy trail. '.repeat(20);
assert.equal(visualDescription({result:{analysis:{assetUnderstanding:{summary:full}}}}),full);
assert.equal(require('../public/asset-understanding.js').normalize({file:{name:'test.mp4'},result:{analysis:{assetUnderstanding:{summary:full}}}}).summary,full.trim());
for(const status of ['ready','cancelled','error'])assert.ok(!pending({status}));
assert.equal(time(125),'2:05');
const root=path.join(__dirname,'../public'),js=fs.readFileSync(path.join(root,'web-analysis.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),css=fs.readFileSync(path.join(root,'web-analysis.css'),'utf8');
assert.match(js,/if\(window.PixfunDesktop\)return/);
assert.match(js,/#analysis\//);assert.match(js,/store=>store.get\(id\)/,'Direct links restore saved results');
assert.doesNotMatch(js,/store\.clear|store\.delete|deleteDatabase|\.showModal\(\).*mediaDetail/,'Old media is not deleted; no detail modal');
assert.match(js,/xhr\.upload\.onprogress/);assert.match(js,/xhr\.onabort/);assert.match(js,/xhr\.ontimeout/);
assert.match(js,/token!==task/,'Cancelled analysis cannot replace newer results');
assert.doesNotMatch(js,/innerHTML|hookScore|structureScore|formatGuess/,'No unsafe markup or fabricated backend heuristics');
for(const title of ['Editing summary','Content','Capture','Editing suggestions','Quality','Audio','Transcript','File details'])assert.ok(js.includes(`'${title}'`));
assert.deepEqual(editingSummary('Theme: Summer travel\nKey shots: Dune; valley; swing\nSuggested use: Dune as opener\nWatch out: Existing titles'),[['Theme','Summer travel'],['Key shots','Dune; valley; swing'],['Suggested use','Dune as opener'],['Watch out','Existing titles']]);
assert.deepEqual(editingSummary(full),[],'Legacy prose stays readable without inventing editing advice');
assert.deepEqual(editingSummary('Theme: Summer\nKey shots: Dune'),[],'Do not silently discard incomplete notes');
assert.match(js,/Full description/,'Long legacy notes are available on demand, not deleted');
assert.match(html,/<section id="webAnalysis" hidden/);assert.match(css,/@media\(max-width:600px\)/);
assert.doesNotMatch(css,/position:sticky|position:fixed/,'Report scrolls as a single page');
console.log('PASS: Single-file web validation, isolated native workflow, saved result routes, truthful sections, cancellation and responsive report.');
